#@ load("@ytt:data", "data")
#@ load("dataflow.star", "service_spec_type")
#@ load("dataflow.star", "service_spec_type_loadbalancer")
#@ load("dataflow.star", "service_spec_allocate_load_balancer_node_ports")
#@ load("dataflow.star", "has_service_spec_load_balancer_class")
#@ load("dataflow.star", "service_spec_load_balancer_class")
kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  annotations:
    kapp.k14s.io/change-group: "scdf.tanzu.vmware.com/server"
    kapp.k14s.io/change-rule.1: "upsert after upserting scdf.tanzu.vmware.com/db"
    kapp.k14s.io/change-rule.2: "upsert after upserting scdf.tanzu.vmware.com/skipper"
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: #@ service_spec_type()
  ports:
  - port: 80
    targetPort: 9393
    name: scdf-server
  #@ if service_spec_type_loadbalancer():
  allocateLoadBalancerNodePorts: #@ service_spec_allocate_load_balancer_node_ports()
    #@ if has_service_spec_load_balancer_class():
  loadBalancerClass: #@ service_spec_load_balancer_class()
    #@ end
  #@ end
  selector:
    app: scdf-server
